/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreateRouteImport } from './routes/create'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authCreateOrganisationRouteImport } from './routes/(auth)/create-organisation'
import { Route as ApiPdfInvoiceIdRouteImport } from './routes/api/pdf/$invoiceId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPdfInvoiceIdSplatRouteImport } from './routes/api/pdf/$invoiceId/$'

const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authCreateOrganisationRoute = authCreateOrganisationRouteImport.update({
  id: '/create-organisation',
  path: '/create-organisation',
  getParentRoute: () => authRouteRoute,
} as any)
const ApiPdfInvoiceIdRoute = ApiPdfInvoiceIdRouteImport.update({
  id: '/api/pdf/$invoiceId',
  path: '/api/pdf/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPdfInvoiceIdSplatRoute = ApiPdfInvoiceIdSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiPdfInvoiceIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/create-organisation': typeof authCreateOrganisationRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pdf/$invoiceId': typeof ApiPdfInvoiceIdRouteWithChildren
  '/api/pdf/$invoiceId/$': typeof ApiPdfInvoiceIdSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/create-organisation': typeof authCreateOrganisationRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pdf/$invoiceId': typeof ApiPdfInvoiceIdRouteWithChildren
  '/api/pdf/$invoiceId/$': typeof ApiPdfInvoiceIdSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/create': typeof CreateRoute
  '/(auth)/create-organisation': typeof authCreateOrganisationRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pdf/$invoiceId': typeof ApiPdfInvoiceIdRouteWithChildren
  '/api/pdf/$invoiceId/$': typeof ApiPdfInvoiceIdSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/create-organisation'
    | '/login'
    | '/signup'
    | '/api/auth/$'
    | '/api/pdf/$invoiceId'
    | '/api/pdf/$invoiceId/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/create-organisation'
    | '/login'
    | '/signup'
    | '/api/auth/$'
    | '/api/pdf/$invoiceId'
    | '/api/pdf/$invoiceId/$'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/create'
    | '/(auth)/create-organisation'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/api/auth/$'
    | '/api/pdf/$invoiceId'
    | '/api/pdf/$invoiceId/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  CreateRoute: typeof CreateRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPdfInvoiceIdRoute: typeof ApiPdfInvoiceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/create-organisation': {
      id: '/(auth)/create-organisation'
      path: '/create-organisation'
      fullPath: '/create-organisation'
      preLoaderRoute: typeof authCreateOrganisationRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/api/pdf/$invoiceId': {
      id: '/api/pdf/$invoiceId'
      path: '/api/pdf/$invoiceId'
      fullPath: '/api/pdf/$invoiceId'
      preLoaderRoute: typeof ApiPdfInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pdf/$invoiceId/$': {
      id: '/api/pdf/$invoiceId/$'
      path: '/$'
      fullPath: '/api/pdf/$invoiceId/$'
      preLoaderRoute: typeof ApiPdfInvoiceIdSplatRouteImport
      parentRoute: typeof ApiPdfInvoiceIdRoute
    }
  }
}

interface authRouteRouteChildren {
  authCreateOrganisationRoute: typeof authCreateOrganisationRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authCreateOrganisationRoute: authCreateOrganisationRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface ApiPdfInvoiceIdRouteChildren {
  ApiPdfInvoiceIdSplatRoute: typeof ApiPdfInvoiceIdSplatRoute
}

const ApiPdfInvoiceIdRouteChildren: ApiPdfInvoiceIdRouteChildren = {
  ApiPdfInvoiceIdSplatRoute: ApiPdfInvoiceIdSplatRoute,
}

const ApiPdfInvoiceIdRouteWithChildren = ApiPdfInvoiceIdRoute._addFileChildren(
  ApiPdfInvoiceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  CreateRoute: CreateRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPdfInvoiceIdRoute: ApiPdfInvoiceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
